### ISSUE TITLE
Python 3 is not supported

### ISSUE THREAD

**Issue by Symmetric** [upwork/python-upwork#10]
Have you thought about how you will support Python 3? 

I may have some time to contribute to this, but I want to check if you've done anything on this task first.

**Comment by mnovozhylov** [comment]
@Symmetric ,
currently, we don't plan support of Python 3

**Comment by Symmetric** [comment]
:-1:

By my estimate it's probably a day or so to implement, far less if you're familiar with the code.

Would you take a PR to implement Python 3 support if I end up needing to implement it?

**Comment by mnovozhylov** [comment]
there are a very few requests for python3 support, therefore, we don't want to risk with stability just to have a one new small feature

**Comment by KFoxder** [comment]
+1 Would love to see Python 3 supported.

**Comment by MbarekFiras** [comment]
+1 for Python 3 supprt

**Comment by broc-harcourt** [comment]
+1 for Python 3 support, thank you.

**Comment by abeburnett** [comment]
+1 for Python 3 support. I won't personally use it unless it's moved to Python 3. Upwork needs to move into the future--2.7 may be sufficient and stable, but it's the past.
