### ISSUE TITLE
Page size

### ISSUE THREAD

**Issue by csdenboer** [upwork/python-upwork#12]
Why is the page size restricted to 100, while the FAQ (https://developers.upwork.com/api-faq.html#) states:

Q: Are search results limited to a specific number of results?
A: Yes, Freelancers and Jobs search results are limited to 5,000 results.

Am I missing something or is the FAQ outdated? I think 100 results is rather limited.

Thanks,

Christian

**Comment by mnovozhylov** [comment]
5K is a maximum number of all returned jobs, it has nothing to do with page. Use the parameter `page` to receive other jobs.
