### ISSUE TITLE
How to use upwork client with Django?

### ISSUE THREAD

**Issue by rajasimon** [upwork/python-upwork#17]
HI

I'm developing the application with Django framework. As you know that Django is not keeping the `client` instance across request. I can't find the way to make it work.

```
def access(request):
    client = upwork.Client(public_key, secret_key)
    url = client.auth.get_authorize_url()
    return HttpResponseRedirect(url)
```

```
def authorize(request):
    oauth_verifier = request.GET.get('oauth_verifier')
    oauth_access_token, oauth_access_token_secret = \
        client.auth.get_access_token(oauth_verifier)
```

Though this is not working because again I need to call the get_authorize_url. I don't like this behaviour because I wanted to use `client` instance wherever in the Django environment. Is there any way I can make it work with across request. Like Reddit Praw they have [multi](http://praw.readthedocs.io/en/stable/pages/multiprocess.html#praw-multiprocess) instance. 

Please point me in the right direction...

**Comment by nishuk0007** [comment]
@rajasimon  Hi, Did you get any solution. I'm also struggling with the same issue.

**Comment by mnovozhylov** [comment]
sorry, guys, but I'm closing the thread becayse Django issues / difficulties are not related to this library

**Comment by rajasimon** [comment]
@nishuk0007 I will give you the solution once I done.

**Comment by nishuk0007** [comment]
@rajasimon  Are you near to fix this issue ?

**Comment by nishuk0007** [comment]
@rajasimon I fixed my issue. Did you ?

**Comment by rajasimon** [comment]
@nishuk0007 No. Can you How you did ?

**Comment by nishuk0007** [comment]
@rajasimon  I serialize client object and store for a current loggedin user in DB. and when needed I deserialize it and use it.

**Comment by rajasimon** [comment]
Nice way of doing that! Can you check `cache` that ?

**Comment by nishuk0007** [comment]
yes
