### ISSUE TITLE
Multiple profiles in get_providers not working

### ISSUE THREAD

**Issue by robinsones** [upwork/python-upwork#20]
If I try to get multiple providers in one call of get_provider, e.g.: 

`client.provider.get_provider(provider_ciphertext = ('~0120bf8d6066507040', '~0120bf8d6066507040'))`

I get the error: 

`HTTP401UnauthorizedError: HTTP Error 401: Code 401: Verification of signature failed.`

I have tried at multiple ways of formatting a tuple or list of provider ciphertexts and none of them work. Examining the code implementation, the error seems to result because: 

`'providers/~0120bf8d6066507040;~0120bf8d6066507040'`

is not a valid url

**Comment by joerg-claussen** [comment]
I had the same issue. I changed ';' to the encoded version '%3B' in upwork/routers/provider.py and this helped.

However, I still get regular errors if I ask for too many profiles at the same time. I get an error almost every time when I add 20 profiles to a request, but it is working well enough with 5 profiles per request.

**Comment by mnovozhylov** [comment]
will be fixed in `v1.2.3`
