### ISSUE TITLE
 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by seanauriti** [upwork/python-upwork#22]
Collecting python-upwork
  Downloading python-upwork-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\myuser\AppData\Local\Temp\pip-build-bq1kuaer\python-upwork\setup.py", line 35
        print 'Updating ``upwork/__init__.py`` to version "{0}"'.format(version)
                                                               ^
    SyntaxError: invalid syntax

**Comment by mnovozhylov** [comment]
@seanauriti , the syntax is valid - make sure you use a valid python version. Pay attention that the library is not compatible with Python3

**Comment by seanauriti** [comment]
I'm using Python 2.7

**Comment by mnovozhylov** [comment]
@seanauriti , fyi:
```
$ ls -la setyp.pyc || python --version && python -m py_compile setup.py && ls -la setup.pyc
ls: cannot access 'setyp.pyc': No such file or directory
Python 2.7.12
-rw-rw-r-- 1 m m 3217 Dez 13 10:13 setup.pyc
```

**Comment by seanauriti** [comment]
if I download it and run python setup.py it works, however when I run it from a django project using pip install it doesn't work... I'm on Windows:

![image](https://cloud.githubusercontent.com/assets/7475382/21285512/ab323ba0-c408-11e6-8ee8-f0088382b6f3.png)
