### ISSUE TITLE
Job search result not latest

### ISSUE THREAD

**Issue by rajasimon** [upwork/python-upwork#24]
Please pardon me If this question already asked. 

I like to get the latest jobs using Python-Upwork. 

    https://developers.upwork.com/?lang=python#jobs

And I found that result are not latest and the latest result is one hour ago. Why this behaviour? Or did I missing something?

**Comment by mnovozhylov** [comment]
Thank you for using the library!
Please, note that `python-upwork` library returns a response from the backend - contact the Support Team if you still have the questions regarding this.
