### ISSUE TITLE
get_authorize_url() trouble

### ISSUE THREAD

**Issue by brendancol** [upwork/python-upwork#32]
During the initial oauth dance, I'm experience the following trouble `(Python3) (python-upwork=1.3)`

The code snippet below is returning a `auth_url` without an `oauth_token` url parameter 

Code
------
```python
client = upwork.Client(PUBLIC_KEY, SECRET_KEY)
auth_url = client.auth.get_authorize_url()
webbrowser.open(url=auth_url, autoraise=True, new=2)
print('Go to the mentioned URL : {}'.format(auth_url))
verifier = input('Enter Verifier: ')
```

Result
------
```
print(auth_url)
>>> https://....?**oauth_token=None**
```

My upwork app key has `freelancer search / public profiles` permission and ENABLED status.

Any idea whats going on here?  I just looking to be able to do freelance queries.

**Comment by mnovozhylov** [comment]
Sorry, Python 3 is not officially supported by this library.
Still, you can try locally with this pull request - #27

**Comment by webyneter** [comment]
This is still an issue now, even after that PR was merged.

**Comment by webyneter** [comment]
The workaround:

```python
from upwork.oauth import OAuth


def _patched_get_request_token(self: OAuth):
    """
    Addresses
    https://github.com/upwork/python-upwork/issues/32

    Reference: upwork.oauth.get_request_token
    """
    from upwork.oauth import oauth, urlparse

    client = oauth.Client(self.get_oauth_consumer())
    response, content = client.request(self.request_token_url, "POST")

    # This does the trick:
    content = content.decode("utf-8")

    if response.get("status") != "200":
        raise Exception("Invalid request token response: {0}.".format(content))
    request_token = dict(urlparse.parse_qsl(content))
    self.request_token = request_token.get("oauth_token")
    self.request_token_secret = request_token.get("oauth_token_secret")
    return self.request_token, self.request_token_secret


OAuth.get_request_token = _patched_get_request_token
```

**Comment by webyneter** [comment]
@mnovozhylov, `client.auth.get_authorize_url()` returns a string of the following format: `https://www.upwork.com/services/api/auth?oauth_token=a14aa57341563769bc18cc5756e5efcd` -- what should I pass to `client.auth.get_access_token()` as the `verifier` argument? My Upwoork API key is configured for "Desktop" use.
