### ISSUE TITLE
Usage of .iteritems() doesn't support for python3

### ISSUE THREAD

**Issue by hoanghiep106** [upwork/python-upwork#42]
My project has been migrated to Python3 lately and I figured out that the newest code didn't update the dictionary method `iteritems`.
I found this error the method `offers.send_client_offer`.
Can somebody take a look?

**Comment by hoanghiep106** [comment]
Replacements of `iteritems` to `items` will fix the bug.

**Comment by mnovozhylov** [comment]
@hoanghiep106 , we're working on a fully compatible python 3 library. Please, stay tuned.

**Comment by hoanghiep106** [comment]
@mnovozhylov Hope to hear from you guys soon.
