### ISSUE TITLE
ImportError: cannot import name 'auth'

### ISSUE THREAD

**Issue by temptitle** [upwork/python-upwork#46]
I tried to launch example but I got this error

Traceback (most recent call last):
  File "myapp.py", line 3, in <module>
    from upwork.routers import auth
ImportError: cannot import name 'auth'

**Comment by mnovozhylov** [comment]
Hi @temptitle,

could you please clarify:

1. have you installed the library as described?
2. does your OS allocate it?
3. do you observe the issue only with "auth" module or it's persistent?

I suspect that the cause of the issue is either 1/ or 2/

**Comment by temptitle** [comment]
Hi @mnovozhylov 

1. Yes (ctr-c, ctr-v).
2. How to check that ? (I can't find upwork lib via pip list)
3. No, problem with other import too (excpet "import upwork")

**Comment by aijogja** [comment]
what **python-upwork** version did you used?
I think you are not using latest version (2.0.0)

**Comment by mnovozhylov** [comment]
@temptitle ,
- please, install the library as described in the README. Copy-paste is not recommended way, unless you know what you're doing.
- https://pypi.org/project/python-upwork/
