### ISSUE TITLE
Hourly jobs have budget 0

### ISSUE THREAD

**Issue by qprotex** [upwork/python-upwork#54]
I am almost sure this was working before but now is 0 always

![image](https://user-images.githubusercontent.com/13024779/101268584-8ab5e100-3732-11eb-8171-ed46e6d5533b.png)

**Comment by mnovozhylov** [comment]
@qprotex , could you please [contact our Support Team](https://support.upwork.com/) and provide the details of the request and other required information for further investigation, because this data issue is not related to the library.
