### ISSUE TITLE
Activities router get_list method doesn't allow pagination

### ISSUE THREAD

**Issue by andresmachado** [upwork/python-upwork#56]
Hey guys, 

I'm trying to fetch all activities code by company using:

```python
from upwork.routers.activities import team
team.Api(client).get_list()
```

but it only accepts `company` and `team` parameters. As I have much more than 1000 activities, I can't get the remaining codes as I can't provide pagination params to the method.

May you please take a look at it? 

Thanks!

**Comment by mnovozhylov** [comment]
hi @andresmachado 
Unfortunately, the paging is not supported for the mentioned API. Instead, please, check `List activities for specific engagement (contract)`. At this point of time, we don't plan changing or adding the functionality.
