### ISSUE TITLE
Yosemite. Difficult to locate ca_cert

### ISSUE THREAD

**Issue by kthouz** [upwork/python-upwork#9]
Hi, 

I am having an issue to locate ca_cert on Mac Yosemite. I followed all steps of installation with success. But when I try to 
upwork.Client(key, secret)

it returns an error

Traceback (most recent call last):
  File "/Users/cgirabawe/SideProjects/upwork-project/smartUpwork.py", line 14, in <module>
    smartuw = SmartUpwork(credentials.key[0], credentials.secret[0])
  File "/Users/cgirabawe/SideProjects/upwork-project/smartUpwork.py", line 7, in __init__
    client = upwork.Client(key, secret)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/upwork/client.py", line 118, in __init__
    ca_certs=ca_certs_locater.get(),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ca_certs_locater/__init__.py", line 36, in get
    raise ImportError()
ImportError

I am new to Mac and I think you guys you can help me to turn around the issue.

Thank you

**Comment by sparmett** [comment]
Hey,

I had the same issue, and struggled with this error for a while. I ended up installing via pip Certifi (https://certifi.io/en/latest/). After running `pip install python-certifi`, you can just call `certify.where()`, which will return the path to `cacert.pem`. Looking at `/ca_certs_locater/init.py`, you can now hardcode in this new path to the certification file.

This is probably not the most ideal solution, but it works!

**Comment by kthouz** [comment]
Thank you Spermett. However, it still doesn't work. 
I tried by using the built-in JavaVM cacerts as well (/System/Library/Frameworks/JavaVM.framework/Home/lib/security/cacerts). The upwork.Client() can work now but it now fails at authentication lient.auth.get_request_token().

**Comment by mnovozhylov** [comment]
@kthouz , have you read and followed the requirements and SSL Certificates Note specified at https://pypi.python.org/pypi/python-upwork?

**Comment by kthouz** [comment]
Thank you mnovozhylov. It works now

**Comment by 4doge** [comment]
@mnovozhylov also have the same issue. 
Install by `pip install python-upwork`
Now `pip freeze` return:
httplib2==0.9.2
httplib2.system-ca-certs-locater==0.1.2
oauth2==1.5.211
python-upwork==1.2
urllib3==1.10

**Comment by rraallvv** [comment]
@mnovozhylov I'm having the same issue, and freeze's output is as @4doge's

```
Emulating desktop app
Traceback (most recent call last):
  File "/Volumes/Developer/desktop_app.py", line 21, in <module>
    client = upwork.Client(public_key, secret_key)
  File "/Library/Python/2.7/site-packages/upwork/client.py", line 119, in __init__
    ca_certs=ca_certs_locater.get(),
  File "/Library/Python/2.7/site-packages/ca_certs_locater/__init__.py", line 36, in get
    raise ImportError()
ImportError
```

**Comment by 4doge** [comment]
hey @rraallvv i've fixed that issue by adding `cacert.pem`, you can get it here: https://gist.github.com/4doge/6c6e85e21016a0286553ce4a75fc9e93
After that just set the env variable `HTTPLIB_CA_CERTS_PATH` with path to the `cacert.pem`
e.g. `export HTTPLIB_CA_CERTS_PATH = "/Users/bokshaanton/Dropbox/work/upwork//cacert.pem"`

**Comment by rraallvv** [comment]
@4doge thanks, very much appreciated.

**Comment by rajasimon** [comment]
@4doge Why you have deleted the `cacert.pem` gist ? Where can I access that or How to generate one ?

**Comment by 4doge** [comment]
@rajasimon sorry, remove that gist occasionally.
Here if a new gist url - https://gist.github.com/4doge/105f7f026aa7556a02b99e163dfeb247

**Comment by aijogja** [comment]
I think, the variable env was changed to `UPWORK_SSL_CERT ` (refers to this commit https://github.com/upwork/python-upwork/commit/51462c5a8e16566e5ff709bcdcadfdce66b5dce1#diff-0a651396dfe0f19d9cfe86b7c2dad257)
